// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
)

const addPerson = `-- name: AddPerson :exec
INSERT INTO people (
  name
) VALUES (
  $1
)
`

func (q *Queries) AddPerson(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, addPerson, name)
	return err
}
