version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    environment:
      PEOPLE_PRODUCTION: "false"
      PEOPLE_API_KEY: "xyz"
      PEOPLE_API_PORT: 3999
      PEOPLE_API_HOST: 0.0.0.0
      PEOPLE_DB_URL: "postgres://people:people@db-app:5432/people?sslmode=disable"
      PEOPLE_DB_AES_KEY: "fd2fe6180dd0a94024643ef61bbccd75"
      PEOPLE_LDAP_URL: "foo"
      PEOPLE_LDAP_USERNAME: "bar"
      PEOPLE_LDAP_PASSWORD: "baz"
    ports:
      - 3999:3999
    volumes:
      - .:/src
    depends_on:
      db-app:
        condition: service_healthy
    command: >
      sh -c "tern status &&
        tern migrate && 
        reflex -d none -c reflex.docker.conf;"
  
  db-app:
    image: postgres:16-alpine
    ports:
      - 5432
    user: postgres
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: people
      POSTGRES_PASSWORD: people
    volumes:
      - people-app-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U people -d people"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  people-app-db-data:
    driver: local 
    driver_opts:
      type: none
      device: ./tmp/app_db_data
      o: bind