// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddOrganization implements AddOrganization operation.
//
// Insert/update a single organization record.
//
// POST /add-organization
func (UnimplementedHandler) AddOrganization(ctx context.Context, req *Organization) (r *Organization, _ error) {
	return r, ht.ErrNotImplemented
}

// AddPerson implements AddPerson operation.
//
// Insert/update a single person record.
//
// POST /add-person
func (UnimplementedHandler) AddPerson(ctx context.Context, req *Person) (r *Person, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrganization implements GetOrganization operation.
//
// Get single organization record.
//
// POST /get-organization
func (UnimplementedHandler) GetOrganization(ctx context.Context, req *GetOrganizationRequest) (r *Organization, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrganizations implements GetOrganizations operation.
//
// Get all organization records.
//
// POST /get-organizations
func (UnimplementedHandler) GetOrganizations(ctx context.Context, req *GetOrganizationsRequest) (r *OrganizationPagedListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrganizationsByIdentifier implements GetOrganizationsByIdentifier operation.
//
// Get organization records by one of the extra identifiers.
//
// POST /get-organizations-by-identifier
func (UnimplementedHandler) GetOrganizationsByIdentifier(ctx context.Context, req *GetOrganizationsByIdentifierRequest) (r *OrganizationListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPeople implements GetPeople operation.
//
// Get all person records.
//
// POST /get-people
func (UnimplementedHandler) GetPeople(ctx context.Context, req *GetPeopleRequest) (r *PersonPagedListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPeopleByIdentifier implements GetPeopleByIdentifier operation.
//
// Retrieve person records by one of the extra identifiers.
//
// POST /get-people-by-identifier
func (UnimplementedHandler) GetPeopleByIdentifier(ctx context.Context, req *GetPeopleByIdentifierRequest) (r *PersonListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPerson implements GetPerson operation.
//
// Retrieve a single person record.
//
// POST /get-person
func (UnimplementedHandler) GetPerson(ctx context.Context, req *GetPersonRequest) (r *Person, _ error) {
	return r, ht.ErrNotImplemented
}

// SetPersonOrcid implements SetPersonOrcid operation.
//
// Update person ORCID.
//
// POST /set-person-orcid
func (UnimplementedHandler) SetPersonOrcid(ctx context.Context, req *SetPersonOrcidRequest) (r *Person, _ error) {
	return r, ht.ErrNotImplemented
}

// SetPersonRole implements SetPersonRole operation.
//
// Update person role.
//
// POST /set-person-role
func (UnimplementedHandler) SetPersonRole(ctx context.Context, req *SetPersonRoleRequest) (r *Person, _ error) {
	return r, ht.ErrNotImplemented
}

// SetPersonSettings implements SetPersonSettings operation.
//
// Update person settings.
//
// POST /set-person-settings
func (UnimplementedHandler) SetPersonSettings(ctx context.Context, req *SetPersonSettingsRequest) (r *Person, _ error) {
	return r, ht.ErrNotImplemented
}

// SetPersonToken implements SetPersonToken operation.
//
// Update person tokens.
//
// POST /set-person-token
func (UnimplementedHandler) SetPersonToken(ctx context.Context, req *SetPersonTokenRequest) (r *Person, _ error) {
	return r, ht.ErrNotImplemented
}

// SuggestOrganizations implements SuggestOrganizations operation.
//
// Search on organization records.
//
// POST /suggest-organizations
func (UnimplementedHandler) SuggestOrganizations(ctx context.Context, req *SuggestOrganizationsRequest) (r *OrganizationListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// SuggestPeople implements SuggestPeople operation.
//
// Search on person records.
//
// POST /suggest-people
func (UnimplementedHandler) SuggestPeople(ctx context.Context, req *SuggestPeopleRequest) (r *PersonListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
