// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddPerson implements addPerson operation.
//
// Upsert a person.
//
// POST /add-person
func (UnimplementedHandler) AddPerson(ctx context.Context, req *Person) error {
	return ht.ErrNotImplemented
}

// GetPerson implements getPerson operation.
//
// Get a person.
//
// POST /get-person
func (UnimplementedHandler) GetPerson(ctx context.Context, req *GetPersonRequest) (r GetPersonRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchPeople implements searchPeople operation.
//
// Search people.
//
// POST /search-people
func (UnimplementedHandler) SearchPeople(ctx context.Context, req *SearchPeopleRequest) (r *PersonHits, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
