openapi: 3.1.0

info:
  title: People Service
  version: 0.0.1

servers:
  - url: /api/v1

paths:
  "/add-person":
    post:
      summary: "Upsert a single person"
      description: "Upsert a single person"
      operationId: "AddPerson"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
        required: true
      responses:
        "200":
          description: "Added person successfully"
        default:
          $ref: "#/components/responses/Error"

security:
  - apiKey: []

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-Api-Key

  responses:
    Error:
      description: Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
      required:
        - code
        - message

    Person:
      type: object
      properties:
        active:
          type: boolean
        name:
          type: string
          minLength: 1
        given_name:
          type: string
          minLength: 1
        family_name:
          type: string
          minLength: 1
        honorific_prefix:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 1
        attributes:
          type: array
          items:
            $ref: "#/components/schemas/Attribute"
        identifiers:
          type: array
          items:
            $ref: "#/components/schemas/Identifier"
          minItems: 1
      required: [active, name, identifiers]

    Attribute:
      type: object
      properties:
        scope:
          type: string
          minLength: 1
        key:
          type: string
          minLength: 1
        value:
          type: string
          minLength: 1
      required: [scope, key, value]

    Identifier:
      type: object
      properties:
        type:
          type: string
          minLength: 1
        value:
          type: string
          minLength: 1
      required: [type, value]
