openapi: 3.1.0

info:
  title: People Service
  version: 0.0.1

servers:
  - url: /api/v1

paths:
  "/get-person":
    post:
      summary: Get a person
      description: Get a person
      operationId: getPerson
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetPersonRequest"
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonRecord"
        "404":
          description: Person not found
          $ref: "#/components/responses/Error"
        default:
          $ref: "#/components/responses/Error"

  "/search-people":
    post:
      summary: "Search people"
      description: "Search people"
      operationId: "searchPeople"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchPeopleRequest"
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonHits"
        default:
          $ref: "#/components/responses/Error"  

  "/add-person":
    post:
      summary: Upsert a person
      description: Upsert a person
      operationId: addPerson
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
        required: true
      responses:
        "200":
          description: Success
        default:
          $ref: "#/components/responses/Error"

security:
  - apiKey: []

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-Api-Key

  responses:
    Error:
      description: Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
      required: [code, message]

    GetPersonRequest:
      type: object
      properties:
        identifier:
          $ref: "#/components/schemas/Identifier"
      required: [identifier]

    SearchPeopleRequest:
      type: object
      properties:
        query:
          type: string
      required: [query]

    Person:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        preferredName:
          type: string
          minLength: 1
        givenName:
          type: string
          minLength: 1
        preferredGivenName:
          type: string
          minLength: 1
        familyName:
          type: string
          minLength: 1
        preferredFamilyName:
          type: string
          minLength: 1
        honorificPrefix:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 1
        username:
          type: string
          minLength: 1
        active:
          type: boolean
        attributes:
          type: array
          items:
            $ref: "#/components/schemas/Attribute"
        identifiers:
          type: array
          items:
            $ref: "#/components/schemas/Identifier"
          minItems: 1
      required: [name, identifiers]

    Attribute:
      type: object
      properties:
        scope:
          type: string
          minLength: 1
        key:
          type: string
          minLength: 1
        value:
          type: string
          minLength: 1
      required: [scope, key, value]

    Identifier:
      type: object
      properties:
        type:
          type: string
          minLength: 1
        value:
          type: string
          minLength: 1
      required: [type, value]
    
    PersonRecord:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        preferredName:
          type: string
          minLength: 1
        givenName:
          type: string
          minLength: 1
        preferredGivenName:
          type: string
          minLength: 1
        familyName:
          type: string
          minLength: 1
        preferredFamilyName:
          type: string
          minLength: 1
        honorificPrefix:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 1
        username:
          type: string
          minLength: 1
        active:
          type: boolean
        attributes:
          type: array
          items:
            $ref: "#/components/schemas/Attribute"
        identifiers:
          type: array
          items:
            $ref: "#/components/schemas/Identifier"
          minItems: 1
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required: [name, identifiers, active, createdAt, updatedAt]

    PersonHits:
      type: object
      properties:
        hits:
          type: array
          items:
            $ref: "#/components/schemas/PersonRecord"
      required: [hits]
