// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/ugent-library/people-service/models"
)

type Organization struct {
	ID        int64
	ParentID  pgtype.Int8
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OrganizationIdentifier struct {
	OrganizationID int64
	Type           string
	Value          string
}

type Person struct {
	ID                  int64
	Name                string
	PreferredName       pgtype.Text
	GivenName           pgtype.Text
	FamilyName          pgtype.Text
	PreferredGivenName  pgtype.Text
	PreferredFamilyName pgtype.Text
	HonorificPrefix     pgtype.Text
	Email               pgtype.Text
	Active              bool
	Username            pgtype.Text
	Attributes          []models.Attribute
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type PersonIdentifier struct {
	PersonID int64
	Type     string
	Value    string
}
