// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/ugent-library/people-service/models"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO people (
  name,
  preferred_name,
  given_name,
  family_name,
  preferred_given_name,
  preferred_family_name,
  honorific_prefix,
  email,
  active,
  username,
  attributes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type CreatePersonParams struct {
	Name                string
	PreferredName       pgtype.Text
	GivenName           pgtype.Text
	FamilyName          pgtype.Text
	PreferredGivenName  pgtype.Text
	PreferredFamilyName pgtype.Text
	HonorificPrefix     pgtype.Text
	Email               pgtype.Text
	Active              bool
	Username            pgtype.Text
	Attributes          []models.Attribute
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.Name,
		arg.PreferredName,
		arg.GivenName,
		arg.FamilyName,
		arg.PreferredGivenName,
		arg.PreferredFamilyName,
		arg.HonorificPrefix,
		arg.Email,
		arg.Active,
		arg.Username,
		arg.Attributes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPersonIdentifier = `-- name: CreatePersonIdentifier :exec
INSERT INTO person_identifiers (
  person_id,
  type,
  value
) VALUES ($1, $2, $3)
`

type CreatePersonIdentifierParams struct {
	PersonID int64
	Type     string
	Value    string
}

func (q *Queries) CreatePersonIdentifier(ctx context.Context, arg CreatePersonIdentifierParams) error {
	_, err := q.db.Exec(ctx, createPersonIdentifier, arg.PersonID, arg.Type, arg.Value)
	return err
}

const deactivatePeople = `-- name: DeactivatePeople :exec
UPDATE people SET active = FALSE
WHERE updated_at < $1
`

func (q *Queries) DeactivatePeople(ctx context.Context, updatedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deactivatePeople, updatedAt)
	return err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM people
WHERE id = $1
`

func (q *Queries) DeletePerson(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePerson, id)
	return err
}

const deletePersonIdentifier = `-- name: DeletePersonIdentifier :exec
DELETE FROM person_identifiers
WHERE type = $1 AND value = $2
`

type DeletePersonIdentifierParams struct {
	Type  string
	Value string
}

func (q *Queries) DeletePersonIdentifier(ctx context.Context, arg DeletePersonIdentifierParams) error {
	_, err := q.db.Exec(ctx, deletePersonIdentifier, arg.Type, arg.Value)
	return err
}

const getPerson = `-- name: GetPerson :one
WITH i AS (
  SELECT i1.person_id, i1.type, i1.value
  FROM person_identifiers i1
  LEFT JOIN  person_identifiers i2 ON i1.person_id = i2.person_id
  WHERE i2.type = $1 AND i2.value = $2	
)
SELECT p.id, p.name, p.preferred_name, p.given_name, p.family_name, p.preferred_given_name, p.preferred_family_name, p.honorific_prefix, p.email, p.active, p.username, p.attributes, p.created_at, p.updated_at, json_agg(json_build_object('type', i.type, 'value', i.value)) AS identifiers
FROM people p, i WHERE p.id = i.person_id
GROUP BY p.id
`

type GetPersonParams struct {
	Type  string
	Value string
}

type GetPersonRow struct {
	ID                  int64
	Name                string
	PreferredName       pgtype.Text
	GivenName           pgtype.Text
	FamilyName          pgtype.Text
	PreferredGivenName  pgtype.Text
	PreferredFamilyName pgtype.Text
	HonorificPrefix     pgtype.Text
	Email               pgtype.Text
	Active              bool
	Username            pgtype.Text
	Attributes          []models.Attribute
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Identifiers         []byte
}

func (q *Queries) GetPerson(ctx context.Context, arg GetPersonParams) (GetPersonRow, error) {
	row := q.db.QueryRow(ctx, getPerson, arg.Type, arg.Value)
	var i GetPersonRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PreferredName,
		&i.GivenName,
		&i.FamilyName,
		&i.PreferredGivenName,
		&i.PreferredFamilyName,
		&i.HonorificPrefix,
		&i.Email,
		&i.Active,
		&i.Username,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Identifiers,
	)
	return i, err
}

const getPersonIdentifiers = `-- name: GetPersonIdentifiers :many
SELECT person_id, type, value
FROM person_identifiers
WHERE person_id = $1
`

func (q *Queries) GetPersonIdentifiers(ctx context.Context, personID int64) ([]PersonIdentifier, error) {
	rows, err := q.db.Query(ctx, getPersonIdentifiers, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonIdentifier
	for rows.Next() {
		var i PersonIdentifier
		if err := rows.Scan(&i.PersonID, &i.Type, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferPersonIdentifier = `-- name: TransferPersonIdentifier :exec
UPDATE person_identifiers SET person_id = ($3)
WHERE type = $1 AND value = $2
`

type TransferPersonIdentifierParams struct {
	Type     string
	Value    string
	PersonID int64
}

func (q *Queries) TransferPersonIdentifier(ctx context.Context, arg TransferPersonIdentifierParams) error {
	_, err := q.db.Exec(ctx, transferPersonIdentifier, arg.Type, arg.Value, arg.PersonID)
	return err
}

const updatePerson = `-- name: UpdatePerson :exec
UPDATE people SET (
  name,
  preferred_name,
  given_name,
  family_name,
  preferred_given_name,
  preferred_family_name,
  honorific_prefix,
  email,
  active,
  username,
  attributes,
  updated_at
) = ($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, CURRENT_TIMESTAMP)
WHERE id = $1
`

type UpdatePersonParams struct {
	ID                  int64
	Name                string
	PreferredName       pgtype.Text
	GivenName           pgtype.Text
	FamilyName          pgtype.Text
	PreferredGivenName  pgtype.Text
	PreferredFamilyName pgtype.Text
	HonorificPrefix     pgtype.Text
	Email               pgtype.Text
	Active              bool
	Username            pgtype.Text
	Attributes          []models.Attribute
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) error {
	_, err := q.db.Exec(ctx, updatePerson,
		arg.ID,
		arg.Name,
		arg.PreferredName,
		arg.GivenName,
		arg.FamilyName,
		arg.PreferredGivenName,
		arg.PreferredFamilyName,
		arg.HonorificPrefix,
		arg.Email,
		arg.Active,
		arg.Username,
		arg.Attributes,
	)
	return err
}
